name: Semantic Releaser

on:
  push:
    branches:
      - master
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: brpaz/action-semantic-release@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

